const http=require('http'),https=require('https'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'public'),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(body))}
function createStripeCheckout(data,req,res){
  if(!process.env.STRIPE_SECRET_KEY)return json(res,200,{demo:true});
  const amount=Math.round(Number(data.amount)*100);if(!Number.isInteger(amount)||amount<100)return json(res,400,{error:'Invalid amount'});
  const host=req.headers.host||'localhost:3000',params=new URLSearchParams({'mode':'payment','success_url':`http://${host}/?payment=success`,'cancel_url':`http://${host}/?payment=cancel`,'line_items[0][price_data][currency]':'eur','line_items[0][price_data][product_data][name]':data.description||'Pin & Pedal repair','line_items[0][price_data][unit_amount]':String(amount),'line_items[0][quantity]':'1'}).toString();
  const api=https.request({hostname:'api.stripe.com',path:'/v1/checkout/sessions',method:'POST',headers:{Authorization:`Bearer ${process.env.STRIPE_SECRET_KEY}`,'Content-Type':'application/x-www-form-urlencoded','Content-Length':Buffer.byteLength(params)}},r=>{let body='';r.on('data',x=>body+=x);r.on('end',()=>{try{let d=JSON.parse(body);json(res,r.statusCode,{checkoutUrl:d.url,error:d.error?.message})}catch{json(res,502,{error:'Stripe response could not be read'})}})});api.on('error',()=>json(res,502,{error:'Stripe could not be reached'}));api.end(params)
}
http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/checkout'&&req.method==='POST'){let body='';req.on('data',x=>body+=x);req.on('end',()=>{try{createStripeCheckout(JSON.parse(body),req,res)}catch{json(res,400,{error:'Invalid request'})}});return}const requested=url.pathname==='/'?'/index.html':url.pathname,file=path.normalize(path.join(root,requested));if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)}).listen(process.env.PORT||3000,()=>console.log('Bike Rescue MVP: http://localhost:3000'));
